FROM jupyter/scipy-notebook

USER root

#python environment is name root

RUN conda install --name root\
    pymongo

#Python environment 2 

RUN conda install --name python2\
    pymongo

USER jovyan

